- action:
  - service: script.shut_it_down
  alias: Shut Down When Away
  condition: []
  id: '1512665448871'
  trigger:
  - entity_id: group.anyone
    from: home
    platform: state
    to: not_home
- id: '1514217421324'
  alias: Back Door Close
  trigger:
  - entity_id: binary_sensor.back_door_sensor
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: sensor.period_of_day
    from: '''night'''
    platform: state
    to: '''dawn'''
  condition: []
  action:
  - delay: 00:05:00
  - data:
      entity_id: switch.patio_light_switch
    service: switch.turn_off
  initial_state: true
- id: '1536118483145'
  alias: PS4 off with TV
  trigger:
  - entity_id: switch.tv_power
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: switch.ps4_command
    state: 'on'
  action:
  - data:
      entity_id: switch.ps4_command
    service: switch.turn_off
- id: '1556493468034'
  alias: Porch Light Off In Morning
  trigger:
  - entity_id: sensor.period_of_day
    platform: state
    to: day
  condition: []
  action:
  - data:
      entity_id: switch.entry_lights_porch
    service: switch.turn_off
