- platform: template
  sensors:
    front_door_unlocked:
      friendly_name: Front Door
      entity_id: lock.front_door_locked
      device_class: safety
      value_template: "{{ is_state('lock.front_door_locked', 'unlocked') }}"
    back_door_open:
      friendly_name: Back Door
      entity_id: binary_sensor.back_door_sensor
      device_class: safety
      value_template: "{{ is_state('binary_sensor.back_door_sensor', 'on') }}"
    garage_door_open:
      friendly_name: Garage Door
      entity_id: sensor.garage_status
      device_class: safety
      value_template: "{{ is_state('sensor.garage_status', 'open') }}"
    stereo:
      friendly_name: Stereo
      entity_id: switch.stereo_plug
      value_template: "{{states.switch.stereo_plug.attributes['current_consumption'] | replace(' W', '') | float > 5 }}"