homeassistant:
  name: !secret home_name
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_elev
  unit_system: !secret home_units
  time_zone: !secret home_time_zone
  
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password

  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages

alarm_control_panel:
  - platform: arlo
api:
arlo:
  username: !secret arlo_user
  password: !secret arlo_password
automation: !include automations.yaml
automation dir: !include_dir_list automations
binary_sensor: !include binary_sensors.yaml
camera: !include camera.yaml
cover: !include covers.yaml
device_tracker: !include device_tracker.yaml
device_sun_light_trigger:
  light_group: group.sunset_lights
  device_group: group.us
group: !include_dir_merge_named groups/
input_boolean: !include booleans.yaml
input_datetime: !include datetimes.yaml
#input_number: !include numbers.yaml
intent_script: !include alexa_intents.yaml
light: !include lights.yaml
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
notify: !include notify.yaml
panel_iframe: !include panels.yaml
rest_command: !include rest_commands.yaml
script: !include_dir_merge_named scripts/
sensor: !include sensors.yaml
switch: !include switches.yaml
wake_on_lan:
wemo: !include wemo.yaml
zwave: !include zwave.yaml

# enable the basics
alexa:
config:
discovery:
  ignore:
    - roku
emulated_hue:
  expose_by_default: false
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-floorplan.html
history:
http:
  api_password: !secret http_password
  trusted_networks:
    - 192.168.1.0/24
    - 20.20.20.0/24
    - 127.0.0.1
    - ::1
    
  #ssl_certificate: /home/homeassistant/dehydrated/certs/fiddlersgreen.duckdns.org/fullchain.pem
  #ssl_key: /home/homeassistant/dehydrated/certs/fiddlersgreen.duckdns.org/privkey.pem
  #base_url: fiddlersgreen.duckdns.org:8123
  #trusted_networks:
  #  - 192.168.1.1/24
  #  - 20.20.20.1/24
logbook:
python_script:
recorder:
  db_url: !secret db_url
  purge_interval: 7
  purge_keep_days: 7
sun:

updater:

logger:
  logs:
    pyarlo: error
    pyHS100.protocol: error
    homeassistant.components.zwave.util: error
    libopenzwave: error
    openzwave: error
    sseclient: error
    homeassistant.components.websocket_api: error
    homeassistant.components.device_tracker.unifi_direct: error