homeassistant:
  name: !secret home_name
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_elev
  unit_system: !secret home_units
  time_zone: !secret home_time_zone

  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages

automation: !include automations.yaml
automation dir: !include_dir_list automations
binary_sensor: !include binary_sensors.yaml
cover: !include covers.yaml
device_tracker: !include device_tracker.yaml
device_sun_light_trigger:
  light_group: group.sunset_lights
  device_group: group.us
group: !include_dir_merge_named groups/
input_boolean: !include booleans.yaml
input_datetime: !include datetimes.yaml
#input_number: !include numbers.yaml
intent_script: !include alexa_intents.yaml
light: !include lights.yaml
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
notify: !include notify.yaml
panel_iframe: !include panels.yaml
rest_command: !include rest_commands.yaml
script: !include_dir_merge_named scripts/
sensor: !include sensors.yaml
switch: !include switches.yaml
wake_on_lan:
zwave: !include zwave.yaml

# enable the basics
alexa:
config:
discovery:
  ignore:
    - roku
emulated_hue:
  expose_by_default: false
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
history:
http:
  api_password: !secret http_password
logbook:
python_script:
recorder:
  db_url: !secret db_url
  purge_interval: 7
  purge_keep_days: 7
sun:
updater:

logger:
  default: info
  logs:
    homeassistant.components.script: debug