homeassistant:
  name: !secret home_name
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: !secret home_elev
  unit_system: !secret home_units
  time_zone: !secret home_time_zone

  customize: !include customize.yaml
  packages:  !include_dir_named packages

# Weather prediction
sensor:
  - platform: yr

group: !include groups.yaml
group dir: !include_dir_merge_named groups
automation: !include automations.yaml
automation dir: !include_dir_list automations
script: !include scripts.yaml

input_datetime:
  sunrise_alarm_time:
    name: Sunrise Lights Start Time
    has_date: false
    has_time: true
    initial: '1970-01-01 04:45'

# for the ssh panel
panel_iframe:
  terminal:
    title: 'Terminal'
    icon: mdi:console
    url: 'http://192.168.0.107:4200'

zwave: !include zwave.yaml
# enable the basics
frontend:
config:
http:
  api_password: !secret http_password
updater:
discovery:
history:
logbook:
sun:
emulated_hue:
  expose_by_default: false
python_script:

