- platform: template
  sensors:
    garage_status:
      friendly_name: 'Garage Door Status'
      value_template: '{% if states.cover.garage %}
          {% if states.cover.garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.garage.attributes["door_state"] == "closing" %}
            Closing
          {% elif states.cover.garage.attributes["door_state"] == "offline" %}
            Offline
          {% else %}
            Unknown
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
    garage_car_present:
      friendly_name: 'Car in Garage'
      value_template: '{% if states.cover.garage %}
          {% if states.cover.garage.state == "open" %}
            Door Open
          {% elif ((states.cover.garage.attributes["distance_sensor"] > 40) and (states.cover.garage.attributes["distance_sensor"] < 100)) %}
            Yes
          {% else %}
            No
          {% endif %}
          {% else %}
          n/a
          {% endif %}'
- platform: time_date
  display_options:
    - 'time'
