- platform: template
  sensors:
    cool_to_temp:
      friendly_name: Cool To Temp
      value_template: >
        {{states.climate.hallway.attributes['target_temp_high']}}
      unit_of_measurement: '°F'
      entity_id: climate.hallway
    heat_to_temp:
      friendly_name: Heat To Temp
      value_template: >
        {{states.climate.hallway.attributes['target_temp_low']}}
      unit_of_measurement: '°F'
      entity_id: climate.hallway
    garage_status:
      friendly_name: 'Garage Door Status'
      value_template: >
        {% if states.cover.garage %}
          {% if states.cover.garage.attributes["door_state"] == "open" %}
            Open
          {% elif states.cover.garage.attributes["door_state"] == "closed" %}
            Closed
          {% elif states.cover.garage.attributes["door_state"] == "opening" %}
            Opening
          {% elif states.cover.garage.attributes["door_state"] == "closing" %}
            Closing
          {% elif states.cover.garage.attributes["door_state"] == "offline" %}
            Offline
          {% else %}
            Unknown
          {% endif %}
        {% else %}
          n/a
        {% endif %}
    garage_car_present:
      friendly_name: 'Car in Garage'
      value_template: >
        {% if states.cover.garage %}
          {% if states.cover.garage.state == "open" %}
            Door Open
          {% elif ((states.cover.garage.attributes["distance_sensor"] > 40) and (states.cover.garage.attributes["distance_sensor"] < 100)) %}
            Yes
          {% else %}
            No
          {% endif %}
         {% else %}
          n/a
        {% endif %}
    front_door_lock_battery:
      friendly_name: Front Door Battery
      value_template: >
        {{ states.zwave.front_door.attributes['battery_level'] }}
      unit_of_measurement: '%'
      icon_template: >
        {% set battery_level = states.zwave.front_door.attributes['battery_level']|default(0)|int %}
        {% set battery_round = (battery_level / 10) |int * 10 %}
        {% if battery_round >= 100 %}
          mdi:battery
        {% elif battery_round > 0 %}
          mdi:battery-{{ battery_round }}
        {% else %}
          mdi:battery-alert
        {% endif %}
    back_door_sensor_battery:
      friendly_name: Back Door Battery
      value_template: >
        {{ states.zwave.back_door.attributes['battery_level'] }}
      unit_of_measurement: '%'
      icon_template: >
            {% set battery_level = states.zwave.back_door.attributes['battery_level']|default(0)|int %}
            {% set battery_round = (battery_level / 10) |int * 10 %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
    period_of_day:
       friendly_name: 'period of the day'
       value_template: >-
         {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
           dusk
         {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
           dawn
         {% elif (states.sun.sun.attributes.elevation) < -8 %}
           night
         {% else %}
           day
         {% endif %}
       icon_template: >-
         {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
           mdi:weather-sunset-down
         {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
           mdi:weather-sunset-up
         {% elif (states.sun.sun.attributes.elevation) < -8 %}
           mdi:weather-night
         {% else %}
           mdi:weather-sunny
         {% endif %}         
- platform: time_date
  display_options:
    - 'time'
- platform: steam_online
  api_key: !secret steam_api
  accounts:
    - !secret cassidy_steam
    - !secret natalie_steam
- platform: darksky
  api_key: !secret darksky_key
  name: home_weather
  monitored_conditions:
    - summary
    - apparent_temperature
    - hourly_summary
    - daily_summary
    - apparent_temperature_max
    - apparent_temperature_min
    - icon
- platform: arlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength