- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  switches:
    stereo:
      friendly_name: 'Stereo'
      command_on: 'JgBQAAABJ5ITEhMSExISEhMSExITEhISEzcUNRQ2EzYUNhM2EzYUNhMSExETEhMSExISEhQ2ExITNhM2EzcTNxI3EzYUERM1FQAE9gABJ0sUAA0FAAAAAAAAAAA=='
      command_off: 'JgBQAAABJ5ITEhMSExISEhMSExITEhISEzcUNRQ2EzYUNhM2EzYUNhMSExETEhMSExISEhQ2ExITNhM2EzcTNxI3EzYUERM1FQAE9gABJ0sUAA0FAAAAAAAAAAA=='
    stereo_up:
      friendly_name: 'Stereo Up'
      command_on: 'JgBQAAABJ5IUERMSEhIUERMSExITERMSEzcTNhM2FDYUNRM3EjcUNhM2ExISEhMSExITEhM2FBETEhM2EzcSNxM3EzYTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ5IUERMSEhIUERMSExITERMSEzcTNhM2FDYUNRM3EjcUNhM2ExISEhMSExITEhM2FBETEhM2EzcSNxM3EzYTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
    stereo_down:
     friendly_name: 'Stereo Down'
     command_on: 'JgBQAAABJ5IUERMSFBESEhMSExITEhITEjcTNhM3EjcTNhM3EzYTNxI3ExITNhMSExITERM3ExITEhI3ExISNxM3EjcTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
     command_off: 'JgBQAAABJ5IUERMSFBESEhMSExITEhITEjcTNhM3EjcTNhM3EzYTNxI3ExITNhMSExITERM3ExITEhI3ExISNxM3EjcTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
    stereo_mute:
     friendly_name: 'Stereo Mute'
     command_on: 'JgBQAAABKJITEhMSEhITEhMSExISEhMSEzcSNxM2EzcTNhQ1EzcTNhMSExITEhM2ExITERM3FBETNhM3EzYTEhQ1EzcSEhM3EgAE9wABJ0sUAA0FAAAAAAAAAAA='
     command_off: 'JgBQAAABKJITEhMSEhITEhMSExISEhMSEzcSNxM2EzcTNhQ1EzcTNhMSExITEhM2ExITERM3FBETNhM3EzYTEhQ1EzcSEhM3EgAE9wABJ0sUAA0FAAAAAAAAAAA='
- platform: tplink
  name: Stereo Plug
  host: 10.10.10.5
  enable_leds: false
- platform: command_line
  switches:
    tv_power:
      command_on: 'wakeonlan 3C:59:1E:F1:A3:66; sleep .25; curl -X POST http://192.168.1.24:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://192.168.1.24:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://192.168.1.24:8060/query/device-info | grep power-mode | sed -e "s:.*<power-mode>DisplayOff</power-mode>:OFF:" -e "s:.*<power-mode>PowerOn</power-mode>:ON:" || echo OFF'
      value_template: '{{ value == "ON" }}'