- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  switches:
    stereo:
      friendly_name: 'Stereo'
      command_on: 'JgBQAAABJ5ITEhMSExISEhMSExITEhISEzcUNRQ2EzYUNhM2EzYUNhMSExETEhMSExISEhQ2ExITNhM2EzcTNxI3EzYUERM1FQAE9gABJ0sUAA0FAAAAAAAAAAA=='
      command_off: 'JgBQAAABJ5ITEhMSExISEhMSExITEhISEzcUNRQ2EzYUNhM2EzYUNhMSExETEhMSExISEhQ2ExITNhM2EzcTNxI3EzYUERM1FQAE9gABJ0sUAA0FAAAAAAAAAAA=='
    stereo_up:
      friendly_name: 'Stereo Up'
      command_on: 'JgBQAAABJ5IUERMSEhIUERMSExITERMSEzcTNhM2FDYUNRM3EjcUNhM2ExISEhMSExITEhM2FBETEhM2EzcSNxM3EzYTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ5IUERMSEhIUERMSExITERMSEzcTNhM2FDYUNRM3EjcUNhM2ExISEhMSExITEhM2FBETEhM2EzcSNxM3EzYTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
    stereo_down:
      friendly_name: 'Stereo Down'
      command_on: 'JgBQAAABJ5IUERMSFBESEhMSExITEhITEjcTNhM3EjcTNhM3EzYTNxI3ExITNhMSExITERM3ExITEhI3ExISNxM3EjcTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ5IUERMSFBESEhMSExITEhITEjcTNhM3EjcTNhM3EzYTNxI3ExITNhMSExITERM3ExITEhI3ExISNxM3EjcTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
    stereo_mute:
      friendly_name: 'Stereo Mute'
      command_on: 'JgBQAAABKJITEhMSEhITEhMSExISEhMSEzcSNxM2EzcTNhQ1EzcTNhMSExITEhM2ExITERM3FBETNhM3EzYTEhQ1EzcSEhM3EgAE9wABJ0sUAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABKJITEhMSEhITEhMSExISEhMSEzcSNxM2EzcTNhQ1EzcTNhMSExITEhM2ExITERM3FBETNhM3EzYTEhQ1EzcSEhM3EgAE9wABJ0sUAA0FAAAAAAAAAAA='
    hdmi_switch_1:
      friendly_name: 'Nintendo Switch HDMI'
      command_on: 'JgBgAAABMZMWERURFRAVERURFREVERU0FjUWNBY1FTUWNRU1FjQWERURFTUVERURFTUVERURFREVNBYRFTUVNRYRFTQWNRY0FgAFJQABMkgWAAxrAAEzRxYADGsAATJIFgANBQAAAAAAAAAA'
      command_off: 'JgBgAAABMZMWERURFRAVERURFREVERU0FjUWNBY1FTUWNRU1FjQWERURFTUVERURFTUVERURFREVNBYRFTUVNRYRFTQWNRY0FgAFJQABMkgWAAxrAAEzRxYADGsAATJIFgANBQAAAAAAAAAA'
    hdmi_switch_2:
      friendly_name: 'Playstation HDMI'
      command_on: 'JgBgAAABMZQUEhQSFBITEhURFBIUEhM3FTYUNhQ3FDYUNxQ2FDcUEhQRFTYUNhQ3FDYUEhQSExMTNxMTFBIUEhQRFDcUNhQ3FAAFJwABMEoUAAxuAAEvSxQADG4AAS9LFAANBQAAAAAAAAAA'
      command_off: 'JgBgAAABMZQUEhQSFBITEhURFBIUEhM3FTYUNhQ3FDYUNxQ2FDcUEhQRFTYUNhQ3FDYUEhQSExMTNxMTFBIUEhQRFDcUNhQ3FAAFJwABMEoUAAxuAAEvSxQADG4AAS9LFAANBQAAAAAAAAAA'
    hdmi_switch_3:
      friendly_name: 'SNES HDMI'
      command_on: 'JgBoAAABMZQTExQSExIUEhQSFBIUEhM3FDcUNhM4FDYTOBQ2FDcUERURFDcUERQSFBIUEhMTExIUNxQSEzcTOBQ2FDcTNxQ2FAAFKAABL0sUAAxvAAEwSRQADG8AAS9LEwAMcAABMEoTAA0F'
      command_off: 'JgBoAAABMZQTExQSExIUEhQSFBIUEhM3FDcUNhM4FDYTOBQ2FDcUERURFDcUERQSFBIUEhMTExIUNxQSEzcTOBQ2FDcTNxQ2FAAFKAABL0sUAAxvAAEwSRQADG8AAS9LEwAMcAABMEoTAA0F'
- platform: tplink
  name: Stereo Plug
  host: 10.10.10.5
  enable_leds: false
- platform: command_line
  switches:
    tv_power:
      command_on: 'wakeonlan 3C:59:1E:F1:A3:66; sleep .25; curl -X POST http://192.168.1.24:8060/keypress/PowerOn'
      command_off: 'curl -X POST http://192.168.1.24:8060/keypress/PowerOff'
      command_state: 'curl -s GET http://192.168.1.24:8060/query/device-info | grep power-mode | sed -e "s:.*<power-mode>DisplayOff</power-mode>:OFF:" -e "s:.*<power-mode>PowerOn</power-mode>:ON:" || echo OFF'
      value_template: '{{ value == "ON" }}'
    ps4_command:
      command_on: 'ps4-waker'
      command_off: 'ps4-waker standby'
      command_state: 'ps4-waker search | grep -q "200 Ok" && (echo "true") || (echo "false")' 
      value_template: '{{ value }}'
      friendly_name: "Playstation 4 command"
- platform: template
  switches:
    ps4:
      friendly_name: Playstation
      value_template: "{{ is_state('switch.ps4_command', 'on') }}"
      turn_on:
        service: script.ps4_on
      turn_off:
        service: script.ps4_off
    netflix:
      friendly_name: Netflix
      value_template: "{{ is_state('sensor.roku_channel', 'Netflix') }}"
      turn_on:
        service: script.netflix
      turn_off:
        service: rest_command.roku_home
    hulu:
      friendly_name: Hulu
      value_template: "{{ is_state('sensor.roku_channel', 'Hulu') }}"
      turn_on:
        service: script.hulu
      turn_off:
        service: rest_command.roku_home
    prime:
      friendly_name: Prime
      value_template: "{{ is_state('sensor.roku_channel', 'Amazon Prime Video') }}"
      turn_on:
        service: script.prime
      turn_off:
        service: rest_command.roku_home