- platform: broadlink
  host: !secret broadlink_ip
  mac: !secret broadlink_mac
  switches:
    stereo:
      friendly_name: 'Stereo'
      command_on: 'JgBQAAABJ5ITEhMSExISEhMSExITEhISEzcUNRQ2EzYUNhM2EzYUNhMSExETEhMSExISEhQ2ExITNhM2EzcTNxI3EzYUERM1FQAE9gABJ0sUAA0FAAAAAAAAAAA=='
      command_off: 'JgBQAAABJ5ITEhMSExISEhMSExITEhISEzcUNRQ2EzYUNhM2EzYUNhMSExETEhMSExISEhQ2ExITNhM2EzcTNxI3EzYUERM1FQAE9gABJ0sUAA0FAAAAAAAAAAA=='
    stereo_up:
      friendly_name: 'Stereo Up'
      command_on: 'JgBQAAABJ5IUERMSEhIUERMSExITERMSEzcTNhM2FDYUNRM3EjcUNhM2ExISEhMSExITEhM2FBETEhM2EzcSNxM3EzYTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABJ5IUERMSEhIUERMSExITERMSEzcTNhM2FDYUNRM3EjcUNhM2ExISEhMSExITEhM2FBETEhM2EzcSNxM3EzYTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
    stereo_down:
     friendly_name: 'Stereo Down'
     command_on: 'JgBQAAABJ5IUERMSFBESEhMSExITEhITEjcTNhM3EjcTNhM3EzYTNxI3ExITNhMSExITERM3ExITEhI3ExISNxM3EjcTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
     command_off: 'JgBQAAABJ5IUERMSFBESEhMSExITEhITEjcTNhM3EjcTNhM3EzYTNxI3ExITNhMSExITERM3ExITEhI3ExISNxM3EjcTEhM2EwAE9gABKEoTAA0FAAAAAAAAAAA='
    stereo_mute:
     friendly_name: 'Stereo Mute'
     command_on: 'JgBQAAABKJITEhMSEhITEhMSExISEhMSEzcSNxM2EzcTNhQ1EzcTNhMSExITEhM2ExITERM3FBETNhM3EzYTEhQ1EzcSEhM3EgAE9wABJ0sUAA0FAAAAAAAAAAA='
     command_off: 'JgBQAAABKJITEhMSEhITEhMSExISEhMSEzcSNxM2EzcTNhQ1EzcTNhMSExITEhM2ExITERM3FBETNhM3EzYTEhQ1EzcSEhM3EgAE9wABJ0sUAA0FAAAAAAAAAAA='