alias: Come home after dark, porch light on
initial_state: True
trigger:
  - platform: state
    entity_id: device_tracker.natalie
    to: 'home'
  - platform: state
    entity_id: device_tracker.cassidy
    to: 'home'
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
action:
  service: switch.turn_on
  data:
    entity_id: switch.entry_lights_porch