alias: We're in bed, shut down
initial_state: True
trigger:
  - platform: state
    entity_id: input_boolean.bed_cassidy
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.bed_natalie
    from: 'off'
    to: 'on'
  - platform: time
    at: '19:00:00'
condition:
  condition: and
  conditions:
    - condition: time
      after: '19:00:00'
      before: '04:00:00'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.bed_cassidy
        state: 'on'
      - condition: state
        entity_id: device_tracker.cassidy
        state: 'not_home'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.bed_natalie
        state: 'on'
      - condition: state
        entity_id: device_tracker.natalie
        state: 'not_home'
action:
  - service: script.shut_it_down