alias: We're in bed, shut down
initial_state: True
trigger:
  - platform: state
    entity_id: lock.front_door_locked
    from: 'unlocked'
    to: 'locked'
condition:
  condition: and
  conditions:
    - condition: time
      after: '01:30:00'
      before: '07:00:00'
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.cassidy
        state: 'not_home'
      - condition: state
        entity_id: device_tracker.natalie
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.bed_natalie
        state: 'on'
      - condition: state
        entity_id: input_boolean.bed_cassidy
        state: 'on'
action:
  - service: homeassistant.turn_off
    entity_id: group.lights
  - service: climate.set_operation_mode
    data:
      entity_id: climate.hallway
      operation_mode: "eco"
    