alias: Morning Lights On
trigger:
  - platform: template
    value_template: '{{ (states.input_datetime.morning_lights_time.attributes.timestamp | int | timestamp_custom("%H:%M", False)) == states.sensor.time.state }}'
condition:
  condition: and
  conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.us
      state: home
action:
  service: homeassistant.turn_on
  entity_id: group.morning_lights