alias: Morning Lights On
initial_state: True
trigger:
  - platform: time
    minutes: '/1'
    seconds: 00
condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == (states.input_datetime.morning_lights_time.attributes.timestamp | int | timestamp_custom("%H:%M", False)) }}'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: group.us
      state: home
action:
  service: homeassistant.turn_on
  entity_id: group.morning_lights