alias: Outdoor Lights On
trigger:
  - platform: state
    entity_id: sensor.period_of_day
    to: 'night'    
action:
  - service: homeassistant.turn_on
    entity_id: group.outdoor_holiday_lights