alias: Sunrise Alarm
trigger:
  - platform: template
    value_template: '{{ (states.input_datetime.sunrise_alarm_time.attributes.timestamp | int | timestamp_custom("%H:%M", False)) == states.sensor.time.state }}'
  - platform: event
    event_type: SUNRISE_LOOP
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.us
      state: 'home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: or
      conditions:
      - condition: state
        entity_id: light.bedroom_lights_level
        state: 'off'
      - condition: template
        value_template: '{% if states.light.bedroom_lights_level.attributes.brightness %}{{states.light.bedroom_lights_level.attributes.brightness <= 150}}{%else%}False{%endif%}'
action:
  - service: python_script.light_step
    data:
      entity_id: light.bedroom_lights_level
      step: 4
  - delay: 00:00:40
  - event: SUNRISE_LOOP

