alias: TV from remote
trigger:
  - platform: state
    entity_id: binary_sensor.tv
  - platform: state
    entity_id: binary_sensor.stereo
action:
  - service_template: input_boolean.turn_{{trigger.to_state.state}}
    entity_id: input_boolean.tv
    