alias: TV from HASS
trigger:
  platform: state
  entity_id: switch.tv_power
action:
  - condition: template
    value_template: '{{ states("switch.tv_power") != states("binary_sensor.stereo") }}'
  - service: switch.toggle
    data:
      entity_id: switch.stereo
    