alias: "Unlock Entry Light On"
initial_state: True
hide_entity: True
trigger:
  platform: state
  #entity_id: lock.schlage_be469nxcen_touchscreen_deadbolt_locked
  entity_id: lock.front_door_locked
  from: 'locked'
  to: 'unlocked'
condition:
  condition: sun
  after: sunset
  after_offset: "-0:30:00"
action:
  service: homeassistant.turn_on
  entity_id: switch.entry_lights_switch
