automation:
  - alias: Web - Lock the door
    initial_state: true
    trigger:
      platform: webhook
      webhook_id: lock_the_door
    action:
      service: lock.lock
      entity_id: lock.front_door_locked
  - alias: Web - Set Device Location
    initial_state: true
    trigger:
      platform: webhook
      webhook_id: set_location
    action:
      service: device_tracker.see
      data_template:
        dev_id: '{{ trigger.json.dev_id }}'
        location_name: '{{ trigger.json.location_name }}'
  - alias: Web - In Bed
    initial_state: true
    trigger:
      platform: webhook
      webhook_id: in_bed
    action:
      service: input_boolean.turn_on
      data_template:
        entity_id: 'input_boolean.bed_{{ trigger.json.name }}'
  - alias: Web - Out Bed
    initial_state: true
    trigger:
      platform: webhook
      webhook_id: out_bed
    action:
      service: input_boolean.turn_off
      data_template:
        entity_id: 'input_boolean.bed_{{ trigger.json.name }}'