automation:
  - alias: Web - Lock the door
    initial_state: true
    trigger:
      platform: webhook
      webhook_id: lock_the_door
    action:
      service: lock.lock
      entity_id: lock.front_door_locked
  